### ISSUE TITLE
ctp登录失败后，无法退出程序

### ISSUE THREAD

**Issue by wlnetman** [sunwangme/bftrader#1]
![Uploading QQ图片20160620101939.png…]()
ver:application's buildtime<debug>: Jun 19 2016 00:29:17
1，配置反了ctp交易与行情的地址后，提示ctp无此功能
2，ctp stop
3，重新配置ctp
4，ctp start
5，ctp stop
6，无法退出程序，提示ctp未停止，但是此时ctp是stop的

**Comment by sunwangme** [comment]
多点几次stop
