### ISSUE TITLE
点击stop键，停止失败，造成点击quit键不能正常退出。

### ISSUE THREAD

**Issue by github59987** [sunwangme/bftrader#3]
点击stop键，停止失败，造成点击quit键不能正常退出。

**Comment by sunwangme** [comment]
问题根源：login不成功，ctpmgr里面stop时候，总是先logout这样就logout失败导致没有自动退出

**Comment by github59987** [comment]
既然有行情信息，就代表，已经login成功了。估计还是ctpmgr里面的逻辑问题了。

**Comment by sunwangme** [comment]
行情是md，交易是td，是td没有登录成功。

**Comment by github59987** [comment]
so ga。谢谢big boss解答。
