### ISSUE TITLE
点击持仓查询，程序崩溃

### ISSUE THREAD

**Issue by mailtostanley** [sunwangme/bftrader#8]
持仓合约不在订阅合约里，Bug重现了

**Comment by sunwangme** [comment]
这个bug应该已经修正了，#3
请提供dump文件，还有你的bftrader的版本（压缩包上面写的），最好用v0.0.7
如果github上传不行，就发qq群

**Comment by sunwangme** [comment]
下载地址：https://github.com/sunwangme/bftrader/releases/tag/v0.0.7
